// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyShopK6.Models;

namespace MyShopK6.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20190804025204_AddRole")]
    partial class AddRole
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyShopK6.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaCt")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DonGia");

                    b.Property<int>("GiamGia");

                    b.Property<int>("MaHh");

                    b.Property<int>("SoLuong");

                    b.HasKey("MaCt");

                    b.HasIndex("MaHh");

                    b.ToTable("CTDonHang");
                });

            modelBuilder.Entity("MyShopK6.Models.DonHang", b =>
                {
                    b.Property<int>("MaDh")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaKh")
                        .HasMaxLength(50);

                    b.Property<DateTime>("NgayDat");

                    b.Property<DateTime?>("NgayGiao");

                    b.Property<int?>("PhuongThucThanhToanMaPt");

                    b.Property<double>("TongTien");

                    b.Property<int?>("TrangThaiMaTt");

                    b.HasKey("MaDh");

                    b.HasIndex("MaKh");

                    b.HasIndex("PhuongThucThanhToanMaPt");

                    b.HasIndex("TrangThaiMaTt");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("MyShopK6.Models.HangHoa", b =>
                {
                    b.Property<int>("MaHh")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DonGia");

                    b.Property<int>("GiamGia");

                    b.Property<string>("Hinh")
                        .HasMaxLength(150);

                    b.Property<int>("MaLoai");

                    b.Property<string>("MaTh")
                        .HasMaxLength(50);

                    b.Property<string>("MoTa");

                    b.Property<int>("SoLuong");

                    b.Property<string>("TenHh")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("MaHh");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaTh");

                    b.ToTable("HangHoa");
                });

            modelBuilder.Entity("MyShopK6.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(150);

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("LastLogin");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("RandomKey")
                        .HasMaxLength(10);

                    b.Property<string>("Role");

                    b.HasKey("MaKh");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("MyShopK6.Models.Loai", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Hinh")
                        .HasMaxLength(150);

                    b.Property<int?>("MaLoaiCha");

                    b.Property<string>("MoTa");

                    b.Property<string>("TenLoai")
                        .HasMaxLength(50);

                    b.HasKey("MaLoai");

                    b.HasIndex("MaLoaiCha");

                    b.ToTable("Loai");
                });

            modelBuilder.Entity("MyShopK6.Models.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("MaPt")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MoTa");

                    b.Property<string>("TenPt")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("MaPt");

                    b.ToTable("PhuongThucThanhToan");
                });

            modelBuilder.Entity("MyShopK6.Models.ThuongHieu", b =>
                {
                    b.Property<string>("MaTh")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(150);

                    b.Property<string>("DienThoai")
                        .HasMaxLength(50);

                    b.Property<string>("Logo")
                        .HasMaxLength(150);

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("MaTh");

                    b.ToTable("ThuongHieu");
                });

            modelBuilder.Entity("MyShopK6.Models.TrangThai", b =>
                {
                    b.Property<int>("MaTt")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenTt")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("MaTt");

                    b.ToTable("TrangThaiDonHang");
                });

            modelBuilder.Entity("MyShopK6.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("MyShopK6.Models.HangHoa", "HangHoa")
                        .WithMany()
                        .HasForeignKey("MaHh")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyShopK6.Models.DonHang", b =>
                {
                    b.HasOne("MyShopK6.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKh");

                    b.HasOne("MyShopK6.Models.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany()
                        .HasForeignKey("PhuongThucThanhToanMaPt");

                    b.HasOne("MyShopK6.Models.TrangThai", "TrangThai")
                        .WithMany()
                        .HasForeignKey("TrangThaiMaTt");
                });

            modelBuilder.Entity("MyShopK6.Models.HangHoa", b =>
                {
                    b.HasOne("MyShopK6.Models.Loai", "Loai")
                        .WithMany()
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyShopK6.Models.ThuongHieu", "ThuongHieu")
                        .WithMany()
                        .HasForeignKey("MaTh");
                });

            modelBuilder.Entity("MyShopK6.Models.Loai", b =>
                {
                    b.HasOne("MyShopK6.Models.Loai", "LoaiCha")
                        .WithMany()
                        .HasForeignKey("MaLoaiCha");
                });
#pragma warning restore 612, 618
        }
    }
}
